smtp:
  address:              smtp.gmail.com
  port:                 587
  domain:               siren.com
  authentication:       plain
  enable_starttls_auto: true
  user_name:            [GMAIL-USER]
  password:             [GMAIL-PASSWORD]

mail:
  sender: siren@acme.com
  host: localhost:3000
  reservation_scheduled:
    receiver: tours@example.com